apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
      annotations:
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "weather-app"
        kube-monkey/kill-mode: "random"
        kube-monkey/kill-value: "100"
    spec:
      containers:
        - name: weather-app
          image: registry.gitlab.com/zivgl66/weatherapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: BG_COLOR
              valueFrom:
                configMapKeyRef:
                  name: env-config-green
                  key: BG_COLOR
      imagePullSecrets: 
      - name: regcred
