apiVersion: v1
kind: Service
metadata:
  name: weather-app
  labels:
    app: weather-app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort:  32300
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    app: weather-app

  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
